# fly.toml app configuration file generated for site-hamza on 2026-09-09T15:25:06Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'site-hamza'
primary_region = 'cdg'

[build]
  dockerfile = 'Dockerfile'

[env]
  ALLOWED_HOSTS = '*'
  PORT = '8080'
  PYTHONUNBUFFERED = '1'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
