# Generated by Django 5.2.17 on 2026-09-09 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الريلز')),
                ('video_url', models.URLField(verbose_name='رابط الفيديو')),
                ('thumbnail_url', models.URLField(blank=True, default='', verbose_name='رابط الصورة المصغرة')),
                ('publisher', models.CharField(default='ء ريلز', max_length=100)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(default='تكنولوجيا', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(default='زائر', max_length=150)),
                ('sender_email', models.EmailField(blank=True, default='', max_length=254)),
                ('title', models.CharField(max_length=200, verbose_name='عنوان التذكرة')),
                ('description', models.TextField(verbose_name='وصف المشكلة')),
                ('status', models.CharField(choices=[('pending', 'بانتظار الرد'), ('in_progress', 'قيد المعالجة'), ('resolved', 'تم حل المشكلة'), ('closed', 'مغلقة')], default='pending', max_length=20)),
                ('admin_reply', models.TextField(blank=True, default='', verbose_name='رد الإدارة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
